name: track_your_dollar
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.3
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  flutter_bloc: ^8.1.5
  fluttertoast: ^8.2.5
  get_it: ^7.7.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true